### PR TITLE
Feature/preview the buffer at point in the other window

### PR DESCRIPTION
**Pull request by blue0513**
Related issue: #5 

preview

## TODO
* [x] Implement
* [x] Check if it works
* [x] Update README

### CODE REVIEW

**Comment by minorugh** [comment]
I tried. I was affected!

A little worry is that the cursor point does not move in the same buffer. 
This feature is a need that can not be 'counsel-switch-buffer', 
but I really want 'point-history'.

**Comment by blue0513** [comment]
Do you mean if a point is in `foo.el` at line:35, `point-history-preview` should set the cursor position at line:35 in `foo.el`?

**Comment by minorugh** [comment]
For example,
in foo.el there are multiple edit points on lines 35 and 100.
Both appear in the list, but the cursor does not move to that point.

**Comment by minorugh** [comment]
The points move properly.
There was no change in the other-window display,
so I misunderstood it.
It is a luxury, but it means that it is easy to understand visually if the point is displayed in the middle of the oyhe-window.  My selfishness has passed. I'm sorry.

**Comment by blue0513** [comment]
@minorugh Thx for the review. Fix it to move the cursor to the line of the target buffer.
Plz fetch and pull this branch, then check it.

**Comment by minorugh** [comment]
I was able to confirm. What a wonderful!

**Comment by blue0513** [comment]
@minorugh Merged this PR. You can use it in master branch :tada:  
Thx for your opinion, this package improved a lot. If you start to like this package, plz star and advertise this package lol

**Pull request merged**
